[general]
port = 6800
token = ""
url = "http://localhost"
startupcmds = ["systemctl --user start aria2d.service"]
restartcmds = ["systemctl --user restart aria2d.service", "notify-send 'Aria2c has been restarted.'"]
# startupcmds = ["aria2d"],
# restartcmds = ["pkill aria2d && sleep 1 && aria2d"],
paginate = false


[appearance]
theme = 0
